server:
  servlet:
    context-path: /train
  port: 108

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lowcode?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true&useSSL=false
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/recognize/*.xml