server:
  port: 8088
  servlet:
    context-path: /daydayup


spring:
  application:
    name: daydayup
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/daydayup?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true&useSSL=false
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

