server:
  port: 8999

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: daydayup
          uri: http://localhost:8088/daydayup
          predicates:
            - Path=/daydayup/**