server:
  port: 8071
  servlet:
    context-path: /web

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lowcode?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true&useSSL=false
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
